hyperhq/hyperd

client/attach.go
client/exec.go
client/hijack.go
client/pod.go
client/replace.go
client/stop.go

Hi Hyper Team!
Tried hyper tonight and it didn't work for me - see the issue I submitted.  I am submitting this pull request with small changes to the help and error messages in the client package.
Thanks for releasing this, it looks very interesting!

some small english changes

---

daemon/stop.go

runv will check it
Signed-off-by: Gao feng <feng@hyper.sh>

remove pod status check

---

docker/build.go
lib/docker/builder/internals.go
lib/docker/builder/internals_darwin.go
lib/docker/builder/pod.go

* fix the `CreatePod` function arguments
* fix the create vm function on darwin
* set the builder ‘s `ForceRemove` flag to `true`

builder bug fixes

---

client/list.go
client/run.go
daemon/create.go
daemon/daemon.go
daemon/list.go
daemon/pod.go
daemon/rename.go
docker/container.go
docker/create.go
lib/docker/daemon/rename.go
server/server.go

You can review the fixes with the following test result:
```
lei@leis-MacBook-Pro:[hyper] (master)$ ./hyper run --name="hahah-puller" puller sh
POD id is pod-pJwnQhPsXB
/ # lei@leis-MacBook-Pro:[hyper] (master)$ ./hyper list
POD ID                      POD Name             VM name    Status
pod-pJwnQhPsXB                  hahah-puller       vm-BfLpyXHExY   running
lei@leis-MacBook-Pro:[hyper] (master)$ ./hyper list container
Container ID                                                      Name                         POD ID    Status
c0331b4a57ab424936aa581261a77e925bc1b0c5ee6abc9969857eeaa63198f9  hahah-puller         pod-pJwnQhPsXB   running
```

add container name to 'list' output and 'rename' restful api

---

client/pull.go

When using this image pull API to pull an image from the registry, the
`X-Registry-Auth` header can be used to include a base64-encoded AuthConfig object.

image pull with credentials

---

client/attach.go
client/exec.go
daemon/daemon.go
daemon/info.go
daemon/list.go
daemon/pod.go
daemon/rename.go
daemon/rm.go
daemon/stop.go
server/server.go
types/container.go
types/pod.go
utils/utils.go

This patch depends on https://github.com/hyperhq/runv/pull/11
```
lei@leis-MacBook-Pro:[hyper] (info)$ ./hyper list
POD ID                      POD Name             VM name    Status
pod-JQJVhUAOEm   test-container-create-ubunt                       pending
pod-KUGIRnBoJL   test-container-create-ubunt                       pending
pod-OtqjplKVjM             puller-0401769358                       pending
pod-bDMJNUHKhv   test-container-create-ubunt                       pending
pod-nIZjtetxvF   test-container-create-ubunt                       pending
lei@leis-MacBook-Pro:[hyper] (info)$ ./hyper start pod-OtqjplKVjM
Successfully started the Pod(pod-OtqjplKVjM)
lei@leis-MacBook-Pro:[hyper] (info)$ curl --http1.0 --request GET "http://127.0.0.1:12345/pod/info?podName=pod-OtqjplKVjM" | …
```

add pod info and container info restful API

---

client/pod.go
client/pull.go
daemon/pod.go

```
lei@leis-MacBook-Pro:[hyper] (pull_login)$ ./hyper create examples/test.pod
latest: Pulling from busybox
cf2616975b4a: Pull complete
6ce2e90b0bc7: Pull complete
8c2e06607696: Pull complete
Digest: sha256:df9e13f36d2d5b30c16bfbf2a6110c45ebed0bfa1ea42d357651bc6c736d5322
Status: Downloaded newer image for busybox:latest
Pod ID is pod-TULrekKtvx
lei@leis-MacBook-Pro:[hyper] (pull_login)$ ./hyper images
REPOSITORY     TAG                 IMAGE ID                           CREATED             VIRTUAL SIZE
puller         latest              100000000000                2015-07-18 06:01:13                 0 B
busybox        latest              8c2e06607696                2015-04-18 06:01:13              2.3 MB
lei@leis-MacBook-Pro:[hyper] (pull_login)$ ./hyper list
POD ID …
```

pull the images in pod file automatically while creating pod

---

daemon/pod.go

this will destroy vm immediately.
rearrange codes by the way.

return error if get user failed

---

Makefile.am
utils/utils.go

define the version in build time

configure the version in code with configured value defined in configure.ac

---

configure.ac

bump up version number to 0.4.0

---

hyperd.go

#pr 70 only probe driver in case the driver is empty string.

pr70 does not probe driver if it is specified in configuration file

---

lib/docker/pkg/devicemapper/devmapper_wrapper.go

fix device mapper build error with go 1.5

---

client/run.go

Now, `hyper` will use image's name as the container's name, but the container's name can only be `^/?[a-zA-Z0-9][a-zA-Z0-9_.-]+$`.  So it will generator a new container's name randomly when the image's name is invalid for the rule of container's name.
```
root@ubuntu:/home/lei/src/github.com/hyperhq/hyper# ./hyper run danielbodart/crazyfast.build
POD id is pod-oRxYYYiucq
root@ubuntu:/home/lei/src/github.com/hyperhq/hyper# ./hyper list container
Container ID                                                      Name                         POD ID    Status
cbd68f11ed4a878d106ad1462aecfbbe1dbbb6c35718c35e26313975e2c5c128  berserk_mcclintock   pod-oRxYYYiucq    failed
```

generator the container's name when the image's name can not be used as container name

---

client/pod.go

```
lei@ubuntu:~/src/github.com/hyperhq/hyper$ ./hyper run centos bash
latest: Pulling from centos
47d44cb6f252: Pull complete
f6f39725d938: Pull complete
f9a8cbc8dd13: Pull complete
f37e6a610a37: Pull complete
0f73ae75014f: Pull complete
Digest: sha256:2d9573acf37315cb8fe2a1420769c3b83f59d8f286fd8898a580578c0d5e66c6
Status: Downloaded newer image for centos:latest
POD id is pod-SHAXfdUdNi
bash-4.2# uname -a
Linux centos-2571400580 4.0.4-hyper #45 SMP Thu Jul 16 00:46:44 CST 2015 x86_64 x86_64 x86_64 GNU/Linux
bash-4.2# lei@ubuntu:~/src/github.com/hyperhq/hyper$
lei@ubuntu:~/src/github.com/hyperhq/hyper$ ./hyper create examples/tomcat.pod
latest: Pulling from tomcat
843e2bded498: Pull complete
8c00acfb0175: Pull complete
8b49fe88b40b: Pull complete
3bdf542c6cd7: Pull complete …
```

fix autopull bugs

---

client/rmi.go

make the no-prune option of 'rmi' command have false default value

make the no-prune option of 'rmi' command have false default value

---

daemon/pod.go

hyper ERROR: Error from daemon's response: stat /var/lib/docker/devicemapper/metadata/efeefa308a6f950fe8136c23cdf9a3316c2af298dbfcbabcbfe81fa350441074: no such file or directory

fix wrong devicemapper path

---

daemon/pod.go
examples/file-mapping.pod

then we can bind host `/etc/resolv.conf` to guest
this will help fix https://github.com/hyperhq/hyper/issues/90
this patch include an example for resolve.conf mapping

allow bind either directory or file for vfs volume driver

---

hyperd.go
lib/docker/daemon/daemon.go
lib/docker/daemon/graphdriver/driver.go

/etc/hyper/config: StorageDriver=drivername
Or
export HYPER_STORAGE_DRIVER=drivername

enable users to set the storage driver

---

daemon/vm.go
lib/docker/builder/internals.go
lib/docker/daemon/graphdriver/vbox/driver.go
lib/docker/daemon/graphdriver/vbox/fsdiff.go

in https://github.com/hyperhq/runv/pull/39 , vm chan has been refactored, and the interface has been changed. update it here.

refactor the vm chan in runv, update the status interface

---

client/pull.go
daemon/daemon.go
daemon/info.go
daemon/pod.go
daemon/rm.go
daemon/servicediscovery.go
daemon/vm.go
server/server.go
servicediscovery/servicediscovery.go

reference
https://github.com/hyperhq/hyperstart/pull/6
https://github.com/hyperhq/runv/pull/30

Service discovery

---

hyper.go

cli: return non-zero value when command return error

---

servicediscovery/servicediscovery.go

remove single quotes of service-discovery exec

---

client/create.go
client/pod.go
client/replace.go
client/rm.go
client/run.go
daemon/pod.go
server/server.go

make the function cleaner and easy to maintain. And a bit more: now both the pod file run
and image in command line run can be attached or detached:
- with `-a` or `--attach`, the pod file run (-p or -k) can run attached to the first container
- with `-d` or `--detach`, the image in cmd line run can run without attaching to the container
pod file `run`:
```
[gnawux@ship hyper]$ ./hyper run -a --rm -p examples/ubuntu.pod
POD id is pod-eBktGVRdLl
root@test-container-create-ubuntu:/# uptime
15:22:28 up 0 min,  0 users,  load average: 0.00, 0.00, 0.00
root@test-container-create-ubuntu:/# uname -a
Linux test-container-create-ubuntu 4.0.4-hyper #45 SMP Thu Jul 16 00:46:44 CST 2015 x86_64 x86_64 x86_64 GNU/Linux
root@test-container-create-ubuntu:/# exit
exit
Successfully attached to …
```

re-organize the command run of cli

---

daemon/pod.go

such as `/var/cache/nginx` in official `nginx` image

add volumes in pod if images contains volumes configuration

---

daemon/daemon.go
daemon/info.go
daemon/list.go
daemon/pod.go

Too many things called Pod
based on https://github.com/hyperhq/runv/pull/46

Rename hypervisor.Pod to hypervisor.PodStatus

---

client/run.go
daemon/pod.go

like shells
together with runv https://github.com/hyperhq/runv/pull/48

use run "-i" or "tty" field to specify whether it is interactive

---

daemon/pod.go

Close logger when pod stopped

---

.gitignore
Makefile.am
configure.ac

move manual operations the makefile

linux container on mac

---

client/run.go

fix fail to start kubernetes pod

---

daemon/pod.go
daemon/pod_test.go

if the pod is not configure with a DNS, write host dns to containers

---

daemon/pod.go

as above, only remove a space in comment, will merge if test passed

fix comments format, caused by #138

---

client/run.go
client/vm.go
daemon/daemon.go
daemon/pod.go
daemon/vm.go
server/server.go

so that we can make create+prepare parallel run with vm launch.
This intents to fix the performance regression introduced by the code formalization

run: launch vm before create pod

---

.travis.yml
hack/lib/hyperstart.sh
hack/lib/init.sh
hack/lib/logging.sh
hack/lib/test.sh
hack/lib/util.sh
hack/lib/version.sh
hack/test-cmd.sh

Hyper regression test framework.

add command test cases

---

hyperd.go

recover the original behavior before 0420389d21b0d9630bec23904ae37d730be77b16

set the deafult value for the flags

---

hyperd.go

update for the new package driverloader

---

daemon/info.go
types/container.go

Add podID to container info api

Add podID to container info api

---

.travis.yml
Makefile.am
configure.ac

add libvirt check in autoconf

---

hack/lib/init.sh
hack/lib/test.sh
hack/pods/insert-file.pod
hack/test-cmd.sh

$ sudo HYPER_RUNTIME=/var/lib/hyper hack/test-cmd.sh
and make sure the stop can kill the hyperd process

let the test-cmd.sh could run locally

---

autogen.sh

check pkg-config in autogen.sh

---

storage/devicemapper/dm.go
storage/devicemapper/dm_nonsupport.go

in order to get the stderr output.

dm: use CombinedOutput to replace Output

---

client/run.go

make the /exitcode  (PR #167) easier

let autoRemove become a client behavior

---

client/attach.go
client/exec.go
client/pod.go
daemon/attach.go
daemon/daemon.go
daemon/exec.go
daemon/pod.go
hyper.go
server/server.go

client use this request to get the exit code of exec.

introduce /exitcode request

---

hack/lib/test.sh
hack/test-cmd.sh

also addressed `run -d`, `rm`, `exec` commands

test pr #167, both run and exec

---

.travis.yml
hack/test-cmd.sh

Add tests for libvirt exec driver.

Add libvirt driver tests

---

package/dist/lib/systemd/system/hyperd.service

Fix vfs mount prolem on CentOS/RHEL

---

hack/lib/test.sh
hack/pods/service.pod
hack/test-cmd.sh

Add tests for hyper services, it also checks if #174 has been fixed.

Add tests for hyper services

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/alexzorin/libvirt-go/libvirt.go

Fix https://github.com/hyperhq/runv/pull/109 https://github.com/hyperhq/runv/pull/108
Depends on https://github.com/hyperhq/runv/pull/110

Fix rbd volume for libvirt driver

---

client/exec.go

fix passing null containerId to server

---

package/dist/etc/hyper/config

update the default configuration

---

daemon/etchosts.go
daemon/pod.go
daemon/rm.go

Add `/etc/hosts` volume for containers.

Setup /etc/hosts for containers

---

README.md

show travis build result of master branch

---

daemon/create.go
daemon/daemon.go
daemon/pod.go
docker/create.go

for example, fedora image
we should send command array to docker code if there are some.

docker will reject to create container if the image do not have default commands

---

.gitignore
package/centos/Dockerfile
package/centos/centos-rpm.pod.in
package/centos/rpm/SPECS/hyper.spec.in
package/centos/rpm/SPECS/hyperstart.spec.in
package/fedora/Dockerfile
package/fedora/fedora-rpm.pod.in
package/fedora/make-rpm.sh
package/fedora/rpm/SPECS/hyper.spec
package/fedora/rpm/SPECS/hyperstart.spec
package/fedora/rpm/build.sh

- libvirt pack in RPM
- fedora support

prepare rpm build for 0.5 release

---

docker/create.go

docker check nil of entrypoint

---

hack/lib/test.sh
hack/pods/hostname-err-char.pod
hack/pods/hostname-err-long.pod
hack/pods/hostname.pod
hack/test-cmd.sh

hyperhq/runv#117 added dedicate hostname field in pod, this is the related test case

test case for hostname field in pod spec

---

client/pause.go
client/unpause.go
daemon/commit.go
daemon/daemon.go
daemon/list.go
daemon/pause.go
server/server.go

based on https://github.com/hyperhq/runv/pull/111

support Pause container for hyper

---

configure.ac
package/centos/make-rpm.sh

release 0.5 of hyper

---

configure.ac

And
HAPPY CHINESE NEW YEAR to ALL

hyper build do not depends on sqlite3-dev any more

---

daemon/vm.go

Online CpuMem for cached vm earlier

---

Makefile.am

avoid recompile for every make

---

daemon/server.go
server/router/container/backend.go
server/router/container/container_routes.go
server/router/pod/backend.go
server/router/pod/pod_routes.go
server/router/system/backend.go
server/router/system/system_routes.go

fix the Uncompatible hyper api
fix issue https://github.com/hyperhq/hyper/issues/214

Uncompatible

---

daemon/pod.go
hack/lib/test.sh
hack/test-cmd.sh

Fix container entrypoint and commands

---

daemon/daemon.go
daemon/pod.go
daemon/podlist.go

avoid iterate the whole pod list for finding a container.

add a container map in podList 

---

client/run.go
client/vm.go
server/router/pod/pod_routes.go

remove vm when running pod failed

---

daemon/attach.go
daemon/daemon.go
daemon/exec.go
daemon/pod.go
servicediscovery/servicediscovery.go

base on https://github.com/hyperhq/runv/pull/125
Fix the bug vm exited before get exit code.

store tty commands in pod

---

client/help_darwin.go
client/help_linux.go
client/load.go
server/router/local/image.go
server/router/local/local.go

Usage:
hyper load [OPTIONS]
Load a image from STDIN or tar archive file
Application Options:
-i, --input=""    Read from a tar archive file, instead of STDIN
Help Options:
-h, --help        Show this help message
Signed-off-by: feisky <feiskyer@gmail.com>

Add hyper load command

---

server/router/local/image.go

push: fix get incorrect reference name

---

daemon/daemon.go
daemon/pod.go
daemon/pod_test.go
daemon/rm.go
daemon/servicediscovery.go

- only one time of container inspect
- use container name in spec in any time
- create volumes in creating time and mount/inject in starting
- use command path and args merged by docker instead merge ourselves.

refactor pod create and start operation

---

daemon/daemon.go

enable debug mode
disable iptables rules
disable nat MASQUERADE rules

update Docker daemon configuration

---

client/run.go

Respect `--entrypoint` in `hyper run` command.

Fix hyper run --entrypoint

---

daemon/vm.go

the vms remain in vmList will be destroyed in daemon.Shutdown

hyperd hup: remove released Vm from vmList

---

daemon/daemon.go
daemon/daemonbuilder/pod.go
daemon/graphdriver/vbox/driver.go
daemon/vm.go
hyperd.go
package/dist/etc/hyper/config

use vm factory

---

daemon/daemon.go
daemon/daemondb/daemondb.go
daemon/pod.go
daemon/podlist.go

the iterator in goleveldb use a shared slice for key/value store, if
we want to use the key, value outside the iteration context, we
should copy the data out with
append([]byte{}, iter.Key()...)
append([]byte{}, iter.Value()...)

fix load from leveldb

---

daemon/info.go
daemon/pod.go

and improve the message in case start failed

only check pod ip if pod is running

---

daemon/info.go
daemon/pod.go

all these parameters have already in pod structures

get pod/container info without inspect

---

daemon/run.go

fix max pod num limitation

---

daemon/pod.go
daemon/run.go

include create workdir and copy data from image to volume,
this job is missed in hyper create.

support to initialize container environment

---

client/images.go

add docker go-units into hyper

---

daemon/etchosts.go
daemon/pod.go
daemon/rm.go
daemon/stop.go

The deault size of tmpfs is 1M

store hosts file in tmpfs

---

hyperd.go

restore pods before accept api

---

daemon/daemon.go

add kernel check in hyper 
to make only linux kernel 3.8.0+ can support hyper daemon

add kernel check in hyper

---

client/exec.go
daemon/exec.go
daemon/server.go
server/router/container/backend.go
server/router/container/exec.go
servicediscovery/servicediscovery.go

enable config whether open terminal for exec

---

daemon/kill.go
daemon/server.go
server/router/container/backend.go
server/router/container/container.go
server/router/container/container_routes.go
server/router/pod/backend.go
server/router/pod/pod.go
server/router/pod/pod_routes.go

```
> curl -X POST "http://127.0.0.1:9999/pod/kill?podName=ubuntu-8001317443&signal=10"
{}
> curl -X POST "http://127.0.0.1:9999/container/kill?container=24d692d4b7ff374ccd831cd2b3b3c9096405065526197105c1559213f7168906&signal=1"
{}
```

add api /pod/kill and /container/kill to send signal to containers

---

daemon/pod.go

fix fail to start pod caused by hosts #268

setup hosts volume on host in start pod

---

LICENSE

update the license

---

daemon/pod.go

remove DockerVolume from pod spec
based on https://github.com/hyperhq/runv/pull/176

 remove DockerVolume from pod spec

---

daemon/graphdriver/vbox/driver.go
daemon/graphdriver/vbox/fsdiff.go

Intend to remove KEEP_VM_AFTER_X operation.

Vbox: use new vm to run pod

---

daemon/daemonbuilder/pod.go
daemon/graphdriver/vbox/driver.go
daemon/graphdriver/vbox/fsdiff.go
daemon/pod.go
daemon/run.go
daemon/vm.go

base on https://github.com/hyperhq/runv/pull/189

remove KEEP_VM_*

---

README.md

Signed-off-by: Daehyeok Mun <daehyeok@gmail.com>

Fixed broken docs links

---

daemon/daemon.go
daemon/pod.go
daemon/vm.go

Add some debug logs

---

daemon/daemon.go
daemon/pod.go
daemon/rm.go
daemon/server.go
daemon/stop.go
daemon/storage.go
storage/devicemapper/dm.go
storage/volumes.go

base on Cleanup https://github.com/hyperhq/runv/pull/195
fix bug https://github.com/hyperhq/hyperd/issues/249

Cleanup volumes and images in hyperd

---

daemon/daemonbuilder/pod.go
daemon/stop.go

add PodWait()

---

configure.ac
package/centos/Dockerfile
package/fedora/Dockerfile

update hyper developers email

---

daemon/pod.go

don't pass null value env to hyperstart

---

client/kill.go

fix output message of hyperctl kill

---

client/api/create.go
client/api/login.go
client/api/misc.go

close http response body to avoid resource leak

close http response body to avoid resource leak

---

daemon/daemonbuilder/pod.go

build: fix incorrect podId in ContainerWait

---

daemon/pod.go
daemon/stop.go

fix https://github.com/hyperhq/hyperd/issues/305

wait cleanup job finished in stop pod

---

daemon/pod.go
daemon/stop.go

cleanup pod resource when prepare pod failed

---

client/pull.go
client/push.go

same as #329 
Get panic when I run command `hyperctl pull` `hyperctl push`  with non-privileged user. 
Fix it.

add err condition avoid panic

---

README.md

Signed-off-by: Daehyeok Mun <daehyeok@gmail.com>

Fixed broken Link for Blog in README

---

hyperd.go

Fixed mistyped word in Usage

---

daemon/daemon.go
hyperd.go

do these checks firstly when we start hyperd. If these checks fail, we don`t need to do other things.

do these checks firstly when we start hyperd

---

daemon/attach.go
daemon/daemon.go
daemon/exec.go
daemon/list.go
daemon/pause.go
daemon/tty.go
daemon/vm.go

fix https://github.com/hyperhq/hyperd/issues/313

protect vmList with lock

---

daemon/pod.go
daemon/storage.go

To work with corresponding runv change https://github.com/hyperhq/runv/pull/269

use UserVolume to describe container image

---

daemon/pod.go
daemon/storage.go

setup containerInfo in PrepareContainer

---

client/attach.go
client/logs.go
daemon/daemon.go
daemon/info.go
daemon/kill.go
daemon/list.go
daemon/logs.go
daemon/pause.go
daemon/pod.go
daemon/pod_test.go
daemon/podlist.go
daemon/rename.go
daemon/rm.go
daemon/run.go
daemon/server.go
daemon/servicediscovery.go
daemon/stop.go
daemon/storage.go
daemon/vm.go
serverrpc/list.go
types/types.pb.go
types/types.proto
utils/utils.go

Extend pod and container info

---

integration/client.go
integration/hyper_test.go
serverrpc/info.go
types/types.pb.go
types/types.proto

add ping gRPC

---

daemon/etchosts.go
daemon/pod.go
daemon/run.go

cleanup pod when create pod failed

---

daemon/kill.go

check if pod is running before kill

---

daemon/servicediscovery.go

servicediscovery: do not create haproxy container again

---

daemon/rm.go

As @feiskyer said in this [pr](https://github.com/kubernetes/frakti/pull/11), I think we should change this response code.

change response code to -2, when we can not find the Pod

---

package/dist/etc/hyper/config

add VmFactoryPolicy examples for template in /etc/hyper/config

---

configure.ac
package/centos/make-rpm.sh
package/centos/rpm/SPECS/hyper-container.spec
package/centos/rpm/SPECS/hyperstart.spec
package/fedora/make-rpm.sh
package/fedora/rpm/SPECS/hyper-container.spec
package/fedora/rpm/SPECS/hyperstart.spec

bump version to 0.6.2

---

daemon/server.go

fix #421 , show digest only image

`images` will show digest only image

---

serverrpc/attach.go

fix the bug that sometimes can't get the output of grpc attach and make the code more robust.
Signed-off-by: Yao Zengzeng <yaozengzeng@zju.edu.cn>

fix output bug of grpc attach

---

package/ubuntu/hypercontainer/debian/control
package/ubuntu/hypercontainer/make-hypercontainer-deb.sh

Support xen in deb pkg

---

client/run.go

use bind mount to close #341 
Now support: hyperctl run -v /host-src:/container-dest -t <images>
Test log:
http://pastebin.com/Wr1mZwEa

add --volume support for hyperctl

---

daemon/vm.go

start logging after associate pod to vm

---

client/images.go
utils/utils.go

PR for https://github.com/hyperhq/hyperd/issues/430

bugfix: hyperctl images panic

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/hyperhq/runv/hypervisor/qemu/qemu_ppc64le.go
Godeps/_workspace/src/github.com/hyperhq/runv/lib/utils/mount_linux.go
configure.ac
package/centos/make-rpm.sh
package/centos/rpm/SPECS/hyper-container.spec
package/centos/rpm/SPECS/hyperstart.spec
package/fedora/make-rpm.sh
package/fedora/rpm/SPECS/hyper-container.spec
package/fedora/rpm/SPECS/hyperstart.spec

release 0.7.0

---

package/dist/lib/systemd/system/hyperd.service
package/ubuntu/hypercontainer/debian/changelog
package/ubuntu/hypercontainer/debian/rules
package/ubuntu/hypercontainer/make-hypercontainer-deb.sh
package/ubuntu/hyperstart/debian/changelog
package/ubuntu/hyperstart/make-hyperstart-deb.sh
package/ubuntu/make-deb.sh

update deb pkg to 0.7.0. And add service file and config file in deb pkg.

update deb pkg to 0.7.0 and add service file and config file

---

client/api/info.go

This stuff is spamming my logs badly

remove superfluous logging

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/hyperhq/runv/hypervisor/init_comm.go

delay version-awared command

---

daemon/pod/provision.go

otherwise it may lead to a panic

should init p.sandbox earlier

---

daemon/pod/decommission.go

WaitProcess has the same timer

remove duplicate timer in stopContainers

---

daemon/pod/exec.go

setup process's envs & workdir same as container

---

daemon/pod/container.go
hack/install-grpc.sh
hack/update-generated-proto.sh
types/types.pb.go
types/types.proto

This PR adds LogPath to container spec, which enables custom container log path.
Refer https://github.com/kubernetes/frakti/issues/40.
cc @gnawux @laijs

Add support for custom container log path

---

daemon/pod/provision.go

fix https://github.com/hyperhq/hyperd/issues/491

add missing setup of default route

---

daemon/pod/networks.go

fix debug message

---

hack/test-cmd.sh

try fix jenkins build

---

client/api/interface.go
client/api/list.go
client/list.go
daemon/list.go
daemon/pod/container.go
daemon/pod/pod.go
daemon/server.go
integration/client.go
integration/hyper_test.go
server/router/pod/backend.go
server/router/pod/pod_routes.go
serverrpc/list.go
types/types.pb.go
types/types.proto

Since ipvs based service have been merged, we don't need this anymore. 
/cc @feiskyer 

Remove auxiliary container support

---

daemon/pod/container.go

hyperctl run --workdir="/var" ...

set workdir to user specifed value

---

client/api/interface.go
client/api/save.go
client/help_linux.go
client/save.go
server/router/local/image.go
server/router/local/local.go

hyperctl save IMAGEID -o outfile

add save command

---

.travis.yml

The previous fedora hosting has retired.

update the lvm download link in travis configuration

---

.travis.yml

travis test with go 1.8

---

.travis.yml
hack/test-cmd.sh

travis test with env matrix

---

storage/graphdriver/rawblock/driver.go

use -d instead of --detach-loop for detaching loop device

---

.travis.yml

disable devicemapper test in travis

---

hack/test-cmd.sh

define test matrix for jenkins or cmdline test

---

Godeps/Godeps.json
daemon/pod/container.go
daemon/pod/decommission.go
daemon/pod/migration.go
daemon/pod/persist.go
daemon/pod/provision.go
daemon/pod/sandbox.go
vendor/github.com/hyperhq/runv/hyperstart/libhyperstart/hyperstart.go
vendor/github.com/hyperhq/runv/hyperstart/libhyperstart/json.go
vendor/github.com/hyperhq/runv/hypervisor/network.go
vendor/github.com/hyperhq/runv/hypervisor/persistence.go
vendor/github.com/hyperhq/runv/hypervisor/vm.go
vendor/github.com/hyperhq/runv/hypervisor/vm_states.go

This PR enable restore running container/sandbox after kill -HUP hyperd.
Following of #511. Relay on https://github.com/hyperhq/runv/pull/441

fix daemon restore after kill -HUP

---

.travis.yml
Makefile.am
configure.ac
daemon/storage.go
hack/test-cmd.sh

add btrfs storage driver

---

.gitignore
hack/lib/test.sh

remove paths with Godeps/_workspace

---

hyperd.go

otherwise hyperd may create untraceable vm since there still
have pod/create request	come in.

close api before release vm

---

daemon/pod/decommission.go

volume should only be removed from a running sandbox

---

hack/lib/test.sh
hack/pods/simple-volume.pod
hack/test-cmd.sh

Add regression test for #542 and #537

---

daemon/pod/container.go

If container image has defined volumes, we need to create them.
w/o this, mysql will fail to start because hyperd cannot find volumes defined in image.

parse image volumes before creating volumes

---

hack/lib/test.sh
hack/test-cmd.sh

To cover #551 and #490.
Take care of https://github.com/hyperhq/hyperd/issues/552

add regression test for image volume and /etc/hosts insertion

---

client/attach.go
client/common_options.go
client/create.go
client/exec.go
client/help_darwin.go
client/help_linux.go
client/run.go

Some of the command line descriptions are out of date. 
And fine tune the run/create options.

update the command line help/description messages

---

configure.ac
package/centos/make-rpm.sh
package/centos/rpm/SPECS/hyper-container.spec
package/centos/rpm/SPECS/hyperstart.spec
package/fedora/make-rpm.sh
package/fedora/rpm/SPECS/hyper-container.spec
package/fedora/rpm/SPECS/hyperstart.spec
package/ubuntu/hypercontainer/debian/changelog
package/ubuntu/hypercontainer/make-hypercontainer-deb.sh
package/ubuntu/hyperstart/debian/changelog
package/ubuntu/hyperstart/make-hyperstart-deb.sh

release v0.8.0

---

Godeps/Godeps.json
vendor/github.com/hyperhq/runv/driverloader/driverloader_darwin.go
vendor/github.com/hyperhq/runv/driverloader/driverloader_linux.go
vendor/github.com/hyperhq/runv/factory/cache/cache.go
vendor/github.com/hyperhq/runv/factory/direct/direct.go
vendor/github.com/hyperhq/runv/factory/factory.go
vendor/github.com/hyperhq/runv/factory/single/single.go
vendor/github.com/hyperhq/runv/factory/template/template.go
vendor/github.com/hyperhq/runv/hyperstart/libhyperstart/json.go
vendor/github.com/hyperhq/runv/hypervisor/container.go
vendor/github.com/hyperhq/runv/hypervisor/context.go
vendor/github.com/hyperhq/runv/hypervisor/hypervisor.go
vendor/github.com/hyperhq/runv/hypervisor/qemu/qemu.go
vendor/github.com/hyperhq/runv/hypervisor/qemu/qemu_arm64.go
vendor/github.com/hyperhq/runv/hypervisor/qemu/qemu_process.go
vendor/github.com/hyperhq/runv/hypervisor/qemu/qmp_handler.go
vendor/github.com/hyperhq/runv/hypervisor/vm.go
vendor/github.com/hyperhq/runv/hypervisor/vm_console.go
vendor/github.com/hyperhq/runv/hypervisor/vm_states.go

update runv package

---

Godeps/Godeps.json
vendor/github.com/hyperhq/runv/hyperstart/libhyperstart/json.go
vendor/github.com/hyperhq/runv/hypervisor/hypervisor.go
vendor/github.com/hyperhq/runv/hypervisor/persistence.go
vendor/github.com/hyperhq/runv/hypervisor/report.go
vendor/github.com/hyperhq/runv/hypervisor/vm.go
vendor/github.com/hyperhq/runv/hypervisor/vm_console.go
vendor/github.com/hyperhq/runv/hypervisor/vm_states.go

include hyperhq/runv#467, hyperhq/runv#468

update runv dep for better logs

---

client/api/interface.go
client/api/misc.go
client/attach.go
client/exec.go
client/run.go
daemon/attach.go

For #579
if it is an tty container, don't wait it exit when getting exitcode

handle detach in client side

---

daemon/pod/container.go

I test about 300 pods like this
```
sudo ./hyperctl run --rm -t --name "hello${i}"  busybox sh -c 'echo hello'
```
And about 4% of them lost their output because stderr closed earlier than stdin.

do not attach stderr log stream for container without tty

---

hack/lib/test.sh
hack/pods/nfs-client.pod

so that we get to see touch output if anything fails.

move nfs volume test client image command out

---

daemon/pod/container.go

should check container start result

---

hack/update-govendor.sh
hack/update-runv.sh
vendor/github.com/hyperhq/runv/hyperstart/libhyperstart/json.go
vendor/github.com/hyperhq/runv/hypervisor/context.go
vendor/github.com/hyperhq/runv/hypervisor/vm.go
vendor/github.com/hyperhq/runv/hypervisor/vm_states.go
vendor/github.com/hyperhq/runv/hypervisor/xen/xen.go
vendor/vendor.json

pr #565 #585 and #607 require vendor update now

Update govendor scripts and update runv vendor

---

daemon/pod/provision.go
vendor/github.com/hyperhq/runv/hyperstart/libhyperstart/hyperstart.go
vendor/github.com/hyperhq/runv/hyperstart/libhyperstart/json.go
vendor/github.com/hyperhq/runv/hypervisor/context.go
vendor/github.com/hyperhq/runv/hypervisor/hypervisor.go
vendor/github.com/hyperhq/runv/hypervisor/vm.go
vendor/github.com/hyperhq/runv/hypervisor/vm_states.go
vendor/vendor.json

When sandbox fails to start, hyperd would proceed adding containers and eventually crash. This PR fix it. Needs https://github.com/hyperhq/runv/pull/488
```
I0412 08:06:54.473448   16553 decommission.go:554] Pod[hello121] sandbox info removed from db
I0412 08:06:54.473453   16553 decommission.go:559] Pod[hello121] tag pod as stopped
I0412 08:06:54.473457   16553 decommission.go:566] Pod[hello121] pod stopped
time="2017-04-12T08:07:26Z" level=debug msg="container mounted via layerStore: /var/lib/hyper/rawblock/mnt/d0c4228cf2a9bbaa21497e077fa70db84b7e8d53d961a59151f64a522c9bace8/rootfs"
I0412 08:07:26.345528   16553 container.go:498] Pod[hello121] Con[(hello121)] create container bcd0082849f0b07fa1ff3653377ed902805a475076343f018000d4dd2376f038 (w/: [])
I0412 08:07:26.345639   16553 …
```

Startpod crashes

---

serverrpc/exec.go

For https://github.com/kubernetes/frakti/issues/120
gRPC exec server side should only return after send last
message(either grpc err or EOF) to client side
/cc @feiskyer @gnawux 

wait in ExecStart before out stream finished

---

Makefile.am
hack/test-cmd.sh
vmlogd.go

need https://github.com/hyperhq/runv/pull/456

use Vmlogd to log vm console log

---

daemon/pod/exec.go

https://github.com/hyperhq/runv/pull/491
fix https://github.com/hyperhq/hyperd/issues/609

setup user/group for container exec

---

daemon/pod/container.go

adjust stream setup for the case container restart
for #539.
need update godep after hyperhq/runv#469 merged. Do not merge yet.

Restart attach

---

vendor/github.com/hyperhq/runv/hypervisor/vm_states.go
vendor/vendor.json

update runV dep for 0.8.1 release

---

configure.ac
package/centos/make-rpm.sh
package/centos/rpm/SPECS/hyper-container.spec
package/centos/rpm/SPECS/hyperstart.spec
package/debian/hypercontainer/debian/changelog
package/debian/hypercontainer/debian/rules
package/debian/hypercontainer/make-hypercontainer-deb.sh
package/debian/hyperstart/debian/changelog
package/debian/hyperstart/make-hyperstart-deb.sh
package/dist/lib/systemd/system/hyper-vmlogd.service
package/fedora/make-rpm.sh
package/fedora/rpm/SPECS/hyper-container.spec
package/fedora/rpm/SPECS/hyperstart.spec
package/ubuntu/hypercontainer/debian/changelog
package/ubuntu/hypercontainer/debian/rules
package/ubuntu/hypercontainer/make-hypercontainer-deb.sh
package/ubuntu/hyperstart/debian/changelog
package/ubuntu/hyperstart/make-hyperstart-deb.sh

merge after #577 & #601 closed

release v0.8.1

---

.gitignore

Ignore vmlogd binary in git repo

---

daemon/pod/provision.go

The init result can be gotten from vm.InitSandbox().

remove call to vm.WaitInit()

---

daemon/storage.go

Kernel dm driver has name length limit < 128 bytes.

dm: limit device name length

---

daemon/pod/networks.go
vendor/github.com/hyperhq/runv/hypervisor/network.go
vendor/vendor.json

ifname in InterfaceDescription represents the nic name of vm
on host, it should not be eth-default, and this will cause
error when multi pod doesn't specify ifname but ip.

fix setting up incorrect nic name

---

vendor/github.com/hyperhq/runv/hypervisor/kvmtool/lkvm_arm64.go
vendor/github.com/hyperhq/runv/hypervisor/kvmtool/lkvm_unsupported.go
vendor/vendor.json

Sync runv arm64 kvmtool

---

cmd/hyperd/Makefile.am
configure.ac
vendor/github.com/hyperhq/runv/hypervisor/xen/xen.go
vendor/github.com/hyperhq/runv/hypervisor/xenpv/xenpv.go
vendor/github.com/hyperhq/runv/hypervisor/xenpv/xenpv_unsupported.go
vendor/github.com/hyperhq/runv/lib/runvxenlight/xenlight-runv.go
vendor/github.com/hyperhq/runv/lib/runvxenlight/xenlight.go
vendor/vendor.json

update vendor to hyperhq/runv#646
> this update fixed xen related build issues introduced by hyperhq/runv#597 and hyperhq/runv#543
fix #678, and possibly fix #690

fix xen build

---

Makefile.am
cmd/hyperctl/Makefile.am
cmd/hyperd/Makefile.am
cmd/vmlogd/Makefile.am

The option is just available in Linux.

Add make option GODEBUG to generate GDB friendly binary

---

vendor/github.com/hyperhq/runv/hypervisor/qemu/network.go
vendor/vendor.json

Update vendor/github.com/hyperhq/runv to runv-1.0.y

---

serverrpc/container.go
serverrpc/exec.go
serverrpc/images.go
serverrpc/info.go
serverrpc/list.go
serverrpc/logs.go
serverrpc/pod.go
serverrpc/portmapping.go
serverrpc/service.go
serverrpc/tty.go

serverrpc: update log to show clear work status

---

vendor/github.com/hyperhq/runv/hypervisor/libvirt/libvirt.go
vendor/github.com/hyperhq/runv/hypervisor/qemu/qemu_amd64.go
vendor/github.com/hyperhq/runv/hypervisor/qemu/qemu_arm64.go
vendor/github.com/hyperhq/runv/hypervisor/qemu/qemu_ppc64le.go
vendor/github.com/hyperhq/runv/hypervisor/qemu/qemu_s390x.go
vendor/github.com/hyperhq/runv/hypervisor/qemu/qmp_handler.go
vendor/vendor.json

Update vendor/github.com/hyperhq/runv to merge gnawux/qmp_session

---

daemon/pod/container.go
daemon/pod/decommission.go
daemon/pod/persist.go
daemon/pod/pod.go
daemon/pod/provision.go

https://github.com/hyperhq/hyperd/pull/708 will hurt the performance.
Change to use snap to handle the issue.

Use snap to handle the lock issue in XPod.updatePodInfo

---

hack/lib/test.sh
hack/pods/user-override.pod

stick irssi image in test cases to specified version

---

serverrpc/info.go

ServerRPC.PodInfo: ServerRPC.ContainerInfo: show clear info in log
