hyperhq/hyperd

daemon/daemon.go, hyperd.go
These two patches are base on runv#10 `https://github.com/hyperhq/runv/pull/10`.
1. get rid of daemon.InitNetwork
2. introduce hyperd flag --noniptables and DisableIptables configuration item.
=> Network related update

autogen.sh
in debian derived distro (in about recent 7-10 years) including
pervasive accessible ubuntu , the default sh is dash instead of
bash, and provide much less features than bash.
if run autogen.sh on ubuntu, will cause
$ ./autogen.sh
./autogen.sh: 8: ./autogen.sh: function: not found
we should avoid to use the bash-only feature.
=> autogen.sh: should not use bash keyword, "function"

client/attach.go, client/hijack.go, client/pod.go, client/replace.go, client/run.go, client/utils.go, daemon/attach.go, daemon/daemon.go, daemon/pod.go, daemon/vm.go, lib/docker/builder/internals.go, lib/docker/daemon/graphdriver/vbox/driver.go, lib/docker/daemon/graphdriver/vbox/fsdiff.go, server/server.go
originally we start pod, then attach tty to it. Then we may miss
the beginning of the tty output. Even miss all the output if the
progress exit at once.
this patch include the hyper part and runv part, to enable
establishing the tty connection before starting pod. The result
will be like:
gnawux@sonic$ ./hyper run busybox ps aux
PID   USER     COMMAND
1 root     /init
2 root     ps aux
Successfully attached to pod(pod-xhZAmXwXCV)
End of CmdExec(), Waiting for hijack to finish.
POD id is pod-xhZAmXwXCV
=> Init tty connection before container run

client/list.go, client/run.go, daemon/exec.go, daemon/list.go, daemon/pod.go, daemon/servicediscovery.go, server/server.go
- do not show the auxiliary containers by default, only show if with `-x` option or
`auxiliary=yes` exist in request URL parameter
- add `-p` option or `pod={pod_id}` in request URL parameter to list only the specified
pod, rather than list all.
with this patch, exec {pod-id} will not exec to the service discovery auxiliary container
=> Improve list functionality

daemon/pod.go, examples/insert-file.pod, storage/aufs/aufs.go, storage/devicemapper/dm.go, storage/files.go, storage/overlay/overlay.go, utils/utils.go
including:
- path could include the filename, then not use the name list in pod/files/?/name
- user/group could be "root" or id, not those in host system
- uri support http/https and file:
- content could be empty
and the new implementation avoid writing multiple tmp files.
example pod:
```
{
"id": "test-inject-file",
"containers" : [{
"name": "file-tester",
"image": "ubuntu:latest",
"workdir": "/",
"command": ["/bin/bash"],
"files": [{
"path": "/root/test/",
"filename": "resolv.conf",
"perm": "0600"
},{
"path": "/root/test/logo.png",
"filename": "logo",
"perm": "0644",
"user": "1000",
"group": "1000"
},{
"path": "/root/test/t1",
"filename": "data",
"perm": "0644"
},{
"path": "/root/test/t2",
"filename": "data2",
"perm": "0755"
},{
"path": "/root/test/t3",
"filename": "corrupt",
"perm": …
```
=> the file insert is rewritten, finish all the functions by design

daemon/pod.go
a golfing problem, due to the scope problem, the err was masked,
and not return error, which will lead to panic
=> fix create fail to panic

Godeps/Godeps.json, Godeps/_workspace/src/github.com/tchap/go-patricia/patricia/children.go, Godeps/_workspace/src/github.com/tchap/go-patricia/patricia/patricia.go, Godeps/_workspace/src/github.com/tchap/go-patricia/patricia/patricia_test.go, client/kill.go, client/pod.go, client/rm.go, client/rmi.go, client/utils.go, server/server.go
* put the pod string into data area of request
* make the resource(service, pod, vm and image) 's delete operation as `DELETE` method
This fix makes the request url clean without pod data, put the pod data string into data area of the request.  And adding `DELETE` operation for resource(such as service, pod, vm and image) 's delete operation.
* kill vm
* old
`POST /vm/kill?vmId=vm-xxxx`
* new
`DELETE /vm?vmId=vm-xxxx`
* remove service
* old
`POST /service/delete"?podId=pod-xxxx&service=xxx`
* new
`DELETE /service?podId=pod-xxxx&service=xxx`
* remove pod
* old
`POST /pod/remove?podId=pod-xxxx`
* new
`DELETE /pod?podId=pod-xxxx`
* remove image
* old
`POST /images/remove?imageId=xxxx`
* new
`DELETE /image?imageId=xxxx`
* create pod
* old
`POST /pod/create?podArgs={"id":"xxx", …
=> put the pod string into data area of request

client/images.go, client/list.go
make the client output be flexible
```
root@ubuntu:/home/lei/src/github.com/hyperhq/hyper# ./hyper list pod
POD ID              POD Name                        VM name             Status
pod-NnnmWrAMhX      seaweedfs-1117462063                                failed
pod-nGOpkBxhtm      test-container-create-busybox                       pending
root@ubuntu:/home/lei/src/github.com/hyperhq/hyper# ./hyper rm pod-nGOpkBxhtm
Pod(pod-nGOpkBxhtm) is successful to be deleted!
root@ubuntu:/home/lei/src/github.com/hyperhq/hyper# ./hyper list pod
POD ID              POD Name               VM name             Status
pod-NnnmWrAMhX      seaweedfs-1117462063                       failed
root@ubuntu:/home/lei/src/github.com/hyperhq/hyper# ./hyper create test.pod
Pod ID is pod-NZosdJusbg …
```
=> format the output of 'images' and 'list'

daemon/pod.go, daemon/stop.go
Don't start pod again if it is running.
And cleanup the vm of pod when stopping pod.
=> fix the problem caused by starting pod many times

daemon/pod.go, daemon/stop.go
if pod is stopped automatically, we should reset pod otherwise
start pod will fail with error:
./hyper ERROR: Error from daemon's response: pod pod-JfRVQkHSZc is already running
=> fix fail to start pod

client/run.go, daemon/daemon.go, daemon/info.go, daemon/pod.go, server/server.go, types/pod.go
Implements #134 
Requires https://github.com/hyperhq/runv/pull/98
Notes: travis will be erroring util https://github.com/hyperhq/runv/pull/98 got merged.
```sh
$ hyper run --label a=b --label c=d nginx
POD id is pod-IdlABgYRDx
$ curl hyper-api/pod/info?podName=pod-IdlABgYRDx | jq .spec.labels
{
"a": "b",
"c": "d"
}
```
=> Add labels for hyper pod

hack/test-cmd.sh
let hyper to specify driver automatically.
=> do not specify kvm hypervisor driver in auto test

servicediscovery/servicediscovery.go
the haproxy configuration of new haproxy image is changed, only
support 1.4 version of haproxy image now.
=> use the 1.4 version of haproxy image

daemon/info.go, types/pod.go
Add cpu/memory to pod info api, so we can check cpu and memory info of pod spec.
```sh
[root@host ~]# curl -s 'hyper-api/pod/info?podName=pod-pNBQIpaHzp'  | jq .spec.memory
128
[root@host ~]# curl -s 'hyper-api/pod/info?podName=pod-pNBQIpaHzp'  | jq .spec.vcpu
1
```
=> Add cpu/memory to pod info api

Godeps/_workspace/src/github.com/alexzorin/libvirt-go/domain.go, daemon/daemon.go, daemon/info.go, server/server.go
* Update libvirt-go deps for block stats
* Add statistics api for hyper Pod (must be in running state)
* Depends on https://github.com/hyperhq/runv/pull/100
```sh
$ curl -s 'http://hyper-api/pod/stats?podId=pod-JdESWNChzK' | jq
{
"block": {
"io_merged_recursive": null,
"io_queue_recursive": null,
"io_service_bytes_recursive": [
{
"major": 253,
"minor": 9,
"name": "sda",
"stat": {
"Read": 33792,
"Write": 33693696
}
},
{
"major": 253,
"minor": 4,
"name": "sdb",
"stat": {
"Read": 7009280,
"Write": 307200
}
}
],
"io_service_time_recursive": null,
"io_serviced_recursive": [
{
"major": 253,
"minor": 9,
"name": "sda",
"stat": {
"Read": 9,
"Write": 31
}
},
{
"major": 253,
"minor": 4,
"name": "sdb",
"stat": {
"Read": 373,
"Write": 30
}
}
],
"io_time_recursive": null,
"io_wait_time_recursive": …
```
=> Add statistics api for hyper Pod

hack/lib/test.sh, hack/pods/with-volume.pod, hack/test-cmd.sh
this depends on the fix of hyperhq/hyperstart#37
the test pod include 2 containers and 2 volume.
- one volume is mapped from the host, and the other is created
- the first container read files on the volume, check the mount point, and echo string; 
- the second container write string to a file on the shared volume
=> test volume sharing, both host to vm and vm to host

client/attach.go, client/run.go
make it easier to process the output of hyper run
=> remove the non-container output for attach and attached run

docker/docker.go, hyperd.go
new options for `hyperd`
```
Usage:
./hyperd [OPTIONS]
Application Options:
--nondaemon            Not daemonize
--config=""            Configuration for ./hyperd
--v=0                  Log level fro V logs
--log_dir              Log directory
--host                 Host address and port for hyperd(such as --host=tcp://127.0.0.1:12345)
--registry_mirror      Prefered docker registry mirror, multiple values separated by a comma
--insecure_registry    Enable insecure registry communication, multiple values separated by a comma
--logtostderr          Log to standard error instead of files
--alsologtostderr      Log to standard error as well as files
Help Options:
-h, --help             Show this help message
```
=> add registry mirror and insecure registry options for hyperd

daemon/daemon.go, daemon/vm.go, hyperd.go, lib/docker/daemon/graphdriver/vbox/driver.go
and hot add cpu/mem when cached vm's cpu or mem is dismatch
the cache is enabled only when VmCachePolicy=cache is set in the
/etc/hyper/config.
it speeds up `hyper run` by 50%~70%.
the slowest part is 'logic cpu online" in the guest, so the future
work would be:
1) speed up it
2) do it when the pod is being created
=> add vmcache functionality

.gitignore, hack/pods/with-volume.pod, package/centos/Dockerfile, package/centos/make-rpm.sh, package/centos/rpm/SPECS/hyperstart.spec.in, package/centos/rpm/SPECS/qemu-hyper.spec, package/centos/rpm/build.sh, package/dist/lib/systemd/system/hyperd.service
- include QEMU package for centOS
- fix mistakes in the previous package files
Based on tests on CentOS 7.2 and user reports, the RPMs fixed the CentOS 7.x installations
=> Update centOS RPM build related files

client/attach.go, client/build.go, client/commit.go, client/create.go, client/exec.go, client/images.go, client/info.go, client/kill.go, client/list.go, client/login.go, client/logout.go, client/logs.go, client/pod.go, client/pull.go, client/push.go, client/replace.go, client/rm.go, client/rmi.go, client/run.go, client/stop.go, client/vm.go
There are several bugs/issue in client command line argument processing, for example
hyper run -t
or
hyper build -t "myrepo/myimg"
the above incorrect command line will lead to client panic.
The other problem details include:
In short `Parse()` process os.Args[1:] and `ParseArgs(args []string)` process `args`
The commands have `args` in command line, such as
func (cli *HyperClient) HyperCmdBuild(args ...string) error
when user types ` hyper build -t "myrepo/myimg"`
- the `args` will be `-t`, `myrepo/myimg`
- the `os.Args` should be `hyper`, `build`, `-t`, `myrepo/myimg`
if we use
args, err := parser.Parse()
the args will be `build`, and if we check if it is empty, it will never be empty,
because it always has a `build` here even if we forget to provide the path
And if we use
args, err := …
=> Fix command line argument process

client/list.go, daemon/list.go
Do not list auxiliary containers by default.
```sh
[root@local ~]# hyper list container
Container ID                                                       Name                                                                           POD ID              Status
a8595b5c984c503346918e48e814b5c62892b7a9bd53fc5e34109a8d551abd8d   kube_c3942e3c-c987-11e5-973f-064a4ed57913_busybox_default_busybox_4_88252a0b   pod-CdFTzmUyKQ      running
[root@local ~]# hyper list container -x
Container ID                                                       Name                                                                           POD ID              Status
ba530ef43240182e5bf6b142ea90ddb41bd1403e90e805e148f73c7c711116ee   busybox_default-service-discovery …
```
=> Fix list of auxiliary containers

client/images.go, client/info.go, daemon/tty.go
client/images.go:96: unreachable code
client/info.go:75: unreachable code
daemon/tty.go:38: missing argument for Errorf("%s"): format reads arg 1,
have only 0 args
=> fix errors from "go tool vet ."

client/commit.go, client/exec.go, client/images.go, client/list.go, client/pod.go, client/rmi.go, client/run.go, client/stop.go
clean up hyper client command line options a bit:
1. hyper rmi -f defaults to false now, because go-flags does not work well with boolean option defaulting to true, in which case false cannot be specified by users. Besides, hyper does support non-force rmi by rejecting it if there is a pos using the image.
2. remove redundant value-name in bool options. go-flags only use it to generate help message and manpage, where bool option would print its own default value anyway.
=> hyper client cmd line option cleanup

daemon/info.go, daemon/podlist.go, types/container.go
- support query with container id, prefix, and name (exact id is prefered)
- if there are more than one container share the specified prefix, will return not error
test results:
[root@h8s-single hyper]# curl http://localhost:9999/v0.5/container/info?container=d29a848c0d58d2660b52d05c6aca2a53d9d464c791e97323c86be7baa3680d3c
{"name":"/busybox-2919434435","containerID":"d29a848c0d58d2660b52d05c6aca2a53d9d464c791e97323c86be7baa3680d3c","podID":"pod-YPEragSJvS","image":"busybox","imageID":"sha256:3240943c9ea3f72db51bea0a2428e83f3c5fa1312e19af017d026f9bcf70f84b","commands":[],"args":[],"workingDir":"/","ports":[],"env":[],"volumeMounts":[],"tty":false,"imagePullPolicy":"","status":{"name":"busybox-2919434435","containerID":"d29a848c0d58d2660b52d05c6aca2a53d9d464c791e97323c86be7baa3680d3c","phase …
=> get tty info from container/info interface

daemon/info.go, types/container.go, types/pod.go
- use unify structure for pod and container info
- update cmd and args, as now it comes from inspect
- use image in spec instead of status, as the new status store image id instead of image name in this field
and keeps the /container/info results exactly same as the result in #232
=> update pod info and container info

client/hijack.go
sendStdin is useless, we don't wait for the stdin,
we only wait for stdout.
sendStdin is bug, when stdin&stdout closed at the same
time, we will blocked forever on sendStdin
=> remove bug sendStdin

README.md
`device-mapper-devel` is required in fresh new env, otherwise `./configure` will report:
```
checking libdevmapper.h usability... no
checking libdevmapper.h presence... no
checking for libdevmapper.h... no
configure: error: Could not find or include libdevmapper.h
```
=> Need clarify device-mapper-devel is needed

daemon/attach.go, daemon/daemon.go, daemon/daemonbuilder/pod.go, daemon/daemondb/daemondb.go, daemon/daemondb/keys.go, daemon/exec.go, daemon/graphdriver/vbox/driver.go, daemon/graphdriver/vbox/fsdiff.go, daemon/info.go, daemon/list.go, daemon/pause.go, daemon/pod.go, daemon/podlist.go, daemon/rename.go, daemon/rm.go, daemon/run.go, daemon/server.go, daemon/servicediscovery.go, daemon/stop.go, daemon/storage.go, daemon/vm.go
- pod list lock is dedicated for pod list internal access now
- set pod return status success only if the pod return with all 0 value, i.e. set failed if user stop it. and some other stop processing adjustment
- move the demon methods about create/start pod to a new file
- move all leveldb code to daemondb package, and remove unnecessary daemon method for those have in daemondb
- remove some old flag or methods, including autoremove, GetPod/RunPod
=> Adjust the locking mechanism in daemon

daemon/pod.go, daemon/storage.go
based on https://github.com/hyperhq/runv/pull/149
inspect container is removed in start, so store mountid to
make sure get the correct mountid.
=> container: store mountid to container info

daemon/logs.go
This is the behavior compatible to docker(tm). However, because hyperctl
always try using stream as tty terminal. Need further modification on hyperctl.
should we do the further improvement in another PR?
=> for non-tty container, write log should use stdcopy

client/info.go
when dealing memory size, use go-units
=> when dealing memory size, use go-units

hyperd.go
the flying vms cost a lot of cpu resource, it will cause things worse
if hyperd try to create more vms before deal with flying vms.
=> Initialize vm factory after restore

daemon/daemon.go, daemon/list.go, daemon/pod.go, daemon/rm.go, daemon/stop.go, hack/test-cmd.sh
- use lock protect unset pod.vm
- when delete, if vm is present, set pod status to be None
- when vm stopped, if status is None, reclaim the resource
- when list, do not display the removed pods
=> rm: if vm in pod is still present, wait it stop before remove resource

daemon/rm.go, hack/lib/test.sh, hack/pods/service.pod
- to run pod and rm, should let it attach, otherwise, the rm will be triggered right after the pod is launch successfully.
- the command line should be `/bin/sh -c "ps aux"`, rather than `/bin/sh -c ps aux`
=> rm: remove pod from podlist at last

daemon/daemonbuilder/pod.go
fix bug when `hyperctl build` on devicemapper storage.
=> ContainerWait() waits until the context closed

.travis.yml
If commands in install return a non-zero exit code,
travis will stop immediately, this will give us explicit
error message.
=> travis-ci: build hyperd in install

package/centos/rpm/build.sh, package/fedora/rpm/build.sh
the USER is set in the Dockerfile and the user is switched to makerpm
when build.sh is called.
=> remove 'su makerpm' when build rpm

client/images.go
Get panic when I run command `hyperctl images` with non-privileged user. 
Fix it.
=> add err condition avoid panic

daemon/daemon.go
use EnableDebug method encapsulated by docker
If merged, hyperd code (except `Godeps`) will not include any `logrus` imports
=> remove direct dependency of logrus

daemon/pod.go, daemon/stop.go
depends on https://github.com/hyperhq/runv/pull/242
after vm.StartPod, pod event handler may or may not run, it's
difficult to know if we should wait pod event handler.
Do the waiting in runv.
=> do not wait cleanup job finished in hyperd

daemon/run.go
We don't need check running pod limitation in `CreatePod`, while `RestartPod` should be checked. So move check to `StartInternal`
And the `=` should be kept to ensure that we only support 1024 pods.
=> fix running pod limitation check

integration/client.go, integration/hyper_test.go, serverrpc/images.go, serverrpc/pod.go, types/types.pb.go, types/types.proto
gRpc implementation for:
1. SetPodLabels
2. PodStats
Use `io.Pipe` to replace `buffer` in ImagePull, since there's data race and caused nil pointer in buffer Truncate
=> Implement rpc for SetPodLabels and PodStats

client/api/interface.go, client/api/logs.go, client/logs.go, daemon/daemon.go, daemon/logs.go, daemon/pod.go, package/dist/etc/hyper/config
make logs api works like docker logs exactly.
and 
make container logs dir configurable
The default is not changed: `/var/run/hyper/Pods/{Pod ID}/{container ID}-json.log`
Default config (Log section in `/etc/hyper/config`)
```
[Log]
```
If configure as
```
[Log]
PodLogPrefix=/var/run/hyper/containers
PodIdInPath=false
```
logs will appear in `/var/run/hyper/containers/{container ID}-json.log`
=> logs Improve: procedure adjust and path configurable 

README.md
Hyperd needs config file placed under `/etc/hyper/config`, which
requires user to copy it manually. This fix adds this step to install
from source section.
=> Improve instruction of Hyperd

hack/test-cmd.sh, hyperd.go, mac_installer/dist/opt/hyper/static/config/sh.hyper.hyper.plist, package/dist/lib/systemd/system/hyperd.service
The new bahavior is the same as the --nondaemon is always set.
If the user want to launch hyperd as system daemon,
the user should use the system daemon tools such as systemd.
=> deprecate the flag --nondaemon

hack/test-cmd.sh, servicediscovery/servicediscovery.go
since commit 30b3bf772ba9fb258ef5a4c7d125eca0584ef4ff of
hyperstart, the processes of container will be killed when
container init is exited. in haproxy 1.4 image, haproxy seems
like will fork child process and exit immediately, this cause
service discovery lose effect.
=> servicediscovery: use haproxy1.5 image

daemon/list.go, daemon/servicediscovery.go
Rename service container to random string to avoid conflicts after restarted hyperd.
cc @feiskyer
=> Randomize service container name

client/run.go
As title, the host-src and container-dest folder should be abspath when 'hyperctl --v'
@laijs
=> Add check host-src and container-dest folder should be abspath

package/dist/etc/hyper/config
BIOS image has been moved out from centos rpm.
Cbfs is triggering bug #439
=> Fix #439 : Comment Bios and Cbfs out

client/run.go
otherwise hyperd will ignore the workdir value got from
docker inspect image.
=> hypercli: don't setup workdir for container by default

client/api/create.go, client/api/interface.go, client/api/rm.go, client/api/start.go, client/create.go, client/rm.go, client/run.go, client/start.go, client/stop.go, client/utils.go, daemon/pod/decommission.go, daemon/pod/provision.go, daemon/pod/volume.go, daemon/server.go, hack/pods/with-volume.pod, server/router/container/backend.go, server/router/container/container.go, server/router/container/container_routes.go, serverrpc/container.go, storage/devicemapper/dm.go, types/types.pb.go, types/types.proto
Test results list in following comments.
For #462
=> GRPC interface for Start/Remove container

.travis.yml, client/api/interface.go, client/api/start.go, client/run.go, client/start.go, daemon/daemonbuilder/pod.go, daemon/run.go, daemon/server.go, integration/client.go, integration/hyper_test.go, server/router/pod/backend.go, server/router/pod/pod_routes.go, serverrpc/pod.go, types/types.pb.go, types/types.proto
=> separate start and attach in the client side

utils/sync.go
fmt %#v on error{} does not print error strings as intended:
map[string]error{"1":(*errors.errorString)(0xc82000a310), "2":(*errors.errorString)(0xc82000a330)}
=> error log fix

types/validate.go
Fixes: https://github.com/hyperhq/hyperd/issues/487
Since we do not set volumes in pod anymore (correct me if I'm wrong), why don't remove the validate process?
Signed-off-by: Harry Zhang <harryz@hyper.sh>
=> Remove pod volume validation

integration/client.go, integration/hyper_test.go, serverrpc/container.go, types/types.pb.go, types/types.proto
Signed-off-by: haozhang crazykev@zju.edu.cn
=> add grpc api of container signal

daemon/pod/container.go
We will not create the log dir for now, if custom container log dir do not exist.
cc @feiskyer 
=> Fix custom container log dir do not exist

daemon/daemon.go
Foreach() holds the reader-lock for the podlist,
but p.Dissociate() reqired the writer-lock to remove the containers,
it results deadlock.
=> fix deadlock in ReleaseAllVms()

daemon/daemon.go, daemon/daemondb/daemondb.go, daemon/pod/container.go, daemon/pod/decommission.go, daemon/pod/networks.go, daemon/pod/persist.go, daemon/pod/provision.go, daemon/pod/sandbox.go
1. add saveSandbox() to save runv sandbox persistence info.
2. implement some workflow in save/restore pod data.
3. fix some bugs.
For now, this PR could only support not running pod restore, others will be fixed in next PR in runv/hyperd.
=> fix daemon restore

Godeps/Godeps.json, examples/nfs-volume.pod, hack/lib/test.sh, hack/pods/nfs-client.pod, hack/test-cmd.sh, types/validate.go, vendor/github.com/hyperhq/runv/api/helpers.go, vendor/github.com/hyperhq/runv/hypervisor/context.go, vendor/github.com/hyperhq/runv/hypervisor/disk.go, vendor/github.com/hyperhq/runv/hypervisor/hypervisor.go, vendor/github.com/hyperhq/runv/hypervisor/qemu/qmp_handler.go, vendor/github.com/hyperhq/runv/hypervisor/vm.go
The PR imports runv nfs support (https://github.com/hyperhq/runv/pull/417) and adds nfs volumes support to hyperd, with a podfile example listed.
podfile example:
```
{
"resource": {
"vcpu": 1,
"memory": 1024
},
"containers": [{
"image": "bergwolf/ubuntu-fio",
"volumes": [{
"volume": "sharevolume",
"path": "/export",
"readOnly": false
}]
}],
"volumes": [{
"name": "sharevolume",
"source": "192.168.80.72:/home/bergwolf",
"format": "nas",
"fstype": "nfs"
}]
}
```
```
[hypervsock@~]$sudo hyperctl run -d -p ubuntu.pod
POD id is pod-VVnZwkkoZp
Time to run a POD is 7733 ms
[hypervsock@~]$sudo hyperctl exec -t pod-VVnZwkkoZp bash
root@pod-VVnZwkkoZp:/# df
Filesystem                   1K-blocks      Used Available Use% Mounted on
/dev/sda                     104805376    298180 104507196   1% / …
```
=> support nfs volumes

daemon/daemon.go, daemon/daemondb/daemondb.go, daemon/pod/migration.go
field `driver` in UserVolume have been renamed to `format`, I added it back for compatibility.
Should I just revert 'format' back to 'driver'?
I've test it in aufs/devicemapper + default/qemu combination, works fine. I've some issue running libvirt driver in my local environment, but it should be fine, since this is only concerned with hyperd part data.
Sandbox part will be fixed and tested in hyperhq/runv#441
/cc @laijs
=> Migrate lagecy persistent data to current layout before restore daemon

daemon/storage.go, storage/graphdriver/rawblock/driver.go
```
The driver creates raw-file-block for every images/valume.
It likes vfs driver in the operation creating an image from
the parent. Both drivers do the operation by copying, but
rawblock driver tries to copy the parent by reflink.
So the copy-on-write is supported for the rawblock driver
if the backing(host) filesystem supports copy-on-write.
If the backing filesystem is btrfs, rawblock driver
supports copy-on-write now. If the backing filesystem
is xfs, the rawblock driver will test whether it is
reflink-enabled, if true, rawblock driver supports
copy-on-write.
rawblock driver vs vfs driver:
hypervisor handles block better than dir(9p, sharefs).
rawblock driver supports copy-on-write
rawblock driver vs devicemapper:
loopback-based devicemapper is too ugly.
rawblock driver (will) use …
```
=> add new StorageDriver: rawblock

Godeps/Godeps.json, client/api/exec.go, client/api/hijack.go, client/api/interface.go, client/exec.go, daemon/exec.go, daemon/pod/exec.go, hack/lib/test.sh, hack/test-cmd.sh, server/router/container/backend.go, server/router/container/container.go, server/router/container/exec.go, serverrpc/exec.go, types/types.pb.go, types/types.proto, vendor/github.com/hyperhq/runv/hypervisor/vm.go
This PR adds ExecVM API and its client to hyperd.
Depends on https://github.com/hyperhq/runv/pull/443.
```sh
busybox
depmod
iptables
iptables-restore
iptables-save
ipvsadm
modprobe
mount.nfs4
busybox
depmod
iptables
iptables-restore
iptables-save
ipvsadm
modprobe
mount.nfs4
```
=> Add ExecVM API

daemon/pod/container.go
Docker config user field supports:
[ user | user:group | uid | uid:gid | user:gid | uid:group ]
We need to translate it into runv spec.
```
[hypervsock@hyperhq]$sudo hyperctl run -d gcr.io/google_containers/k8s-dns-sidecar-amd64:1.14.1
POD id is k8s-dns-sidecar-amd64-1.14.1-9540546015
Time to run a POD is 4702 ms
[hypervsock@hyperhq]$sudo hyperctl list
POD ID                                    POD Name                                  VM name             Status
k8s-dns-sidecar-amd64-1.14.1-9540546015   k8s-dns-sidecar-amd64-1.14.1-9540546015   vm-FToockWJoz       running
[hypervsock@hyperhq]$sudo hyperctl exec k8s-dns-sidecar-amd64-1.14.1-9540546015 ps
PID   USER     TIME   COMMAND
1 root       0:00 /init
3 nobody     0:00 /sidecar
7 root       0:00 ps
```
Fixes: …
=> parse docker config user field properly

daemon/pod/container.go, hack/lib/test.sh, hack/pods/user-override.pod, hack/test-cmd.sh
We should respect spec user/group config and override image user/group config if spec user config is present.
Fixes https://github.com/hyperhq/hyperd/issues/548
=> respect spec user config

client/list.go
The original PR was #414 . I have lost some info during rebasing my work so I created a new PR, sorry for the inconvenience. Here are the description from old PR:
While running `docker ps` command, there is a params called `-q`, that only list container ids, without header and other information. The pure id list can be added to some other commands easily, such as `docker stop $(docker ps -aq)`.
This PR added `-q` to `hyperctl list` command to simulate the function. With this params, hyperctl list only shows id for VM / Pod / Container. Please help to review, thanks.
=> [hyperctl / API] Add -q params to `hyperctl list` command

hyperd.go, serverrpc/server.go
when hyperd exiting, the grpc server is closed and
logging error message with glog.Fatalf api, this api
will call os.Exit(255) causing hyperd exit and has no
chance to destroy vms or do other operations.
=> [grpc]: fix possible leak of vm

daemon/pod/decommission.go
introduced from #559, `select` also consume a `break`, we need `return` here.
/cc @feiskyer related with test failure in https://github.com/kubernetes/frakti/pull/113
=> fix break out of for-select

daemon/pod/exec.go
fix #555
before patch:
```
➜ sudo ./hyperctl exec -m busybox-2857568349 sh -c 'echo aaa'
➜ sudo ./hyperctl exec -m busybox-2857568349 sh -c 'echo aaa'
aaa
➜ sudo ./hyperctl exec -m busybox-2857568349 sh -c 'echo aaa'
➜ sudo ./hyperctl exec -m busybox-2857568349 sh -c 'echo aaa'
➜ sudo ./hyperctl exec -m busybox-2857568349 sh -c 'echo aaa'
➜ sudo ./hyperctl exec -m busybox-2857568349 sh -c 'echo aaa'
aaa
➜ sudo ./hyperctl exec -m busybox-2857568349 sh -c 'echo aaa'
aaa
➜ sudo ./hyperctl exec -m busybox-2857568349 sh -c 'echo aaa'
aaa
➜
```
after this patch:
```
➜ for i in `seq 1 1000`; do x=$(sudo ./hyperctl exec -m busybox-1102769742 sh -c 'echo aaa'); [ "${x}x" != "aaax" ] && echo "fail" ; done
➜
```
=> don't interrupt iostream when exec vm process finished

daemon/pod/decommission.go
Fix another bug found in test  `ContainerRemove failed: not a directory` , ref: #540 
could be reproduced when using fs type storage driver and doing "RunPod->StopPod->RmContainer"
=> umount root volume only if pod is running

daemon/pod/container.go, daemon/pod/decommission.go, daemon/pod/migration.go, daemon/pod/pod.go, daemon/pod/provision.go, errors/errors.go
=> fix the race in case sandbox start failed during pod creating

daemon/pod/container.go, daemon/pod/exec.go, daemon/pod/streams.go
fix #604
The container stopping should hup all streams if there are any.
Just check and reclaim any remains after a period should be safe.
Need update #585 later if this is approved
=> Do not close all streams right after container stopped

daemon/pod/provision.go, errors/errors.go
I think this should be the panic cause of #612 
=> check if sandbox create returns no error no result

hack/test-cmd.sh
it truns out that I don't know the vmId when integration test failed.
=> disbale vmlogd in ci

daemon/server.go, libmoby/distribution/fetch_digest.go
This is a work around for #613
We have docker daemon 1.10.3 as vendor, which provides the image DB management functions. However, there is an issue of it, which caused #613.
To fix this, we have three methods
- The work around in this patch
- Update to latest docker vendor
- Introduce an indirect layer for docker vendor
As the docker is changing to moby, we think we will made further update once the moby transition done. And we will apply this simple work around firstly for the 0.8.1 release.
Will introduce two additional (useless actually) manifest fetching, which will slow down a pull progress, esp. when you are far from the registry.
```
➜  sudo ./hyperctl pull busybox
Using default tag: latest
latest: Pulling from library/busybox
7520415ce762: Pull complete
Digest: …
```
=> work around: pull: get digest for tagged pull if it has one

serverrpc/attach.go
Grpc server should close input pipe on client closed.
=> Close input pipe on client closed

.travis.yml
The link in ftp://sources.redhat.com has broken for at least two days,
which broke our CI build.
=> Fix lvm download link for travis CI

storage/aufs/aufs.go
Also add some error logs in case mount(2) fails.
The magic number `54` is a bit mysterious even the very first docker commit (https://github.com/moby/moby/commit/6d97339ca23ada27812572016ad4ff9ccffa8b09 https://github.com/moby/moby/pull/9151) did not bother to explain where it comes from...
Nevertheless, the length calculation when adding dirperm1 is clearly wrong though.
=> fix aufs mount option length calculation

daemon/pod/networks.go, types/types.proto
=> fix incorrect nic name

.travis.yml
Add `go_import_path` to import hyperhq/hyperd.
=> make ci runnable with forked repos

hack/lib/test.sh
So that it is less likely to be killed by the OOM killer.
=> ci: increase memory size of the nfs server

daemon/daemon.go, daemon/storage.go, types/config.go
- add `StorageBaseSize` in hyperd config
- `deviceMapper` will set `Size` as this value if it's larger than 0
@gnawux Can you help review this? Thanks! Didn't find any unit tests for the files I touch so I didn't do any :( Checked the travis config, there is no test using `deviceMapper` as driver, is there a reason why?
Related to https://github.com/hyperhq/hyperd/issues/663
=> add StorageBaseSize in hyperd config

package/centos/rpm/SPECS/hyper-container.spec, package/centos/rpm/SPECS/hyperstart.spec, package/debian/hypercontainer/debian/control, package/debian/hypercontainer/debian/rules, package/debian/hyperstart/debian/control, package/debian/hyperstart/debian/rules, package/fedora/rpm/SPECS/hyper-container.spec, package/fedora/rpm/SPECS/hyperstart.spec, package/ubuntu/hypercontainer/debian/control, package/ubuntu/hypercontainer/debian/rules, package/ubuntu/hyperstart/debian/control, package/ubuntu/hyperstart/debian/rules
- enable the debian/ubuntu deb build for ARM64 arch
- #667 changed the hyperd binary path
- hyperhq/hyperstart#341 changed the kernel path
=> update binary packaging rules for 1.0 build

cmd/hyperd/hyperd.go, daemon/daemon.go, daemon/storage.go, package/dist/etc/hyper/config, storage/graphdriver/rawblock/driver.go, types/config.go
When set, it is used to set both rootfs and volume size for rawblock and devicemapper graph drivers.
e.g., having `StorageBaseSize=3gb`:
```
[root@lear hyper]# hyperctl run -v /data --rm -t busybox
/ # df -h
Filesystem                Size      Used Available Use% Mounted on
/dev/sdb                  3.0G     33.4M      3.0G   1% /
devtmpfs                 53.5M         0     53.5M   0% /dev
tmpfs                    58.1M         0     58.1M   0% /dev/shm
/dev/sda                  3.0G     32.2M      3.0G   1% /data
share_dir                 1.0M      4.0K   1020.0K   0% /etc/hosts
```
cc @minz1027
=> fix storage base size support

.travis.yml, daemon/pod/provision.go, hack/lib/test.sh, hack/test-cmd.sh
fix portmapping failure introduced by hyperhq/runv#592, in which the format of ip field was changed to cidr format.
An test case for portmapping was introduced in this PR.
=> Fix portmapping failure: bad IP address

hack/lib/test.sh, hack/pods/busybox-tty.pod, hack/pods/file-mapping.pod, hack/pods/hostname-err-char.pod, hack/pods/hostname-err-long.pod, hack/pods/hostname.pod, hack/pods/insert-file.pod, hack/pods/nfs-client.pod, hack/pods/readonly-rootfs.pod, hack/pods/service.pod, hack/pods/simple-volume.pod, hack/pods/with-volume.pod, hack/test-cmd.sh, integration/hyper_test.go
Meet a issue that hyper::test::portmapping hang and it is a bug of
busybox image "https://github.com/docker-library/busybox/issues/44"
(It is closed but actually it is not fixed).
After discussion with @gnawux and @bergwolf, all of us think test with a image
that under control is better than use normal busybox image.
So @bergwolf add "hyperhq/busybox" image and let test use it.
=> hack/test-cmd.sh: change test image from "busybox" to "hyperhq/busybox"

daemon/pod/decommission.go
Some resource for containers needs to be released before p.sandbox.Shutdown.
Add this patch to call removeFromSandbox with every p.containers before p.sandbox.Shutdown to release the resource.
=> XPod: doStopPod: call removeFromSandbox with every p.containers

daemon/pod/container.go, daemon/pod/decommission.go, daemon/pod/persist.go, daemon/pod/pod.go, daemon/pod/provision.go
After taking a look at the code, I think the snap xxx is useless.
So I remove snapxxx and add lock to the code that will write p.containers and p.volumes with p.statusLock.Lock().
=> Remove snapContainers and snapVolumes and use other way to handle the lock issue of XPod.updatePodInfo

daemon/pod/networks.go
Now that we've decleared that the Mtu field in types.UserInterface
is optional, we need to provide a default value so that missing
Mtu field won't break interface handling.
=> network: provide a default interface MTU

daemon/pod/decommission.go
fixes #733 
This will deallocate everything physically belonging to a pod right after those same things are deleted from the hyper DB.
=> Decommision pod resources synchronously in Remove() method

client/api/commit.go
Current hyperctl commit will get error if command line has tag.
The reason is tag should be moved out as a special commit option from
repo in hyperctl.
Update Client.Commit to handle the issue.
=> Client.Commit: Fix issue that "commit" command line with tag
